# backend/docker-compose.yml
version: "3.9"

services:
  pulseplan-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      - redis  # Make sure Redis is up before starting the API

  redis:
    image: redis:latest  # Use the latest Redis image
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    restart: always  # Ensure Redis restarts if it fails

