jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Create dummy .env for testing
        run: |
          echo "SECRET_KEY=ci-secret" >> backend/.env
          echo "DATABASE_URL=sqlite:///:memory:" >> backend/.env
          echo "REDIS_HOST=localhost" >> backend/.env
          echo "REDIS_PORT=6379" >> backend/.env
          echo "REDIS_DB=0" >> backend/.env

      - name: Build Docker image and run containers
        run: |
          docker-compose -f backend/docker-compose.yml build  # Build Docker image using Docker Compose
          docker-compose -f backend/docker-compose.yml up -d  # Start Docker container in the background
          docker-compose -f backend/docker-compose.yml ps    # Check if the containers are up

      - name: Run tests in Docker container
        run: |
          docker-compose -f backend/docker-compose.yml exec backend-pulseplan-api-1 pytest  # Run tests inside the Docker container

      - name: Shutdown Docker container
        run: |
          docker-compose -f backend/docker-compose.yml down  # Shutdown Docker container after tests
